# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jekyll Test
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Halvah tootsie roll croissant fruitcake. Ice cream chocolate gummies soufflé chocolate bar brownie liquorice. Lollipop gingerbread cake oat cake gingerbread chocolate bar pastry tart. Lemon drops chocolate bar gummi bears bonbon ice cream lollipop pudding sweet roll biscuit. Biscuit danish bear claw caramels. Dragée chocolate cake bear claw pie chocolate bar. Lemon drops pastry liquorice cake danish caramels. Jujubes wafer chocolate bar. Sugar plum cupcake carrot cake cake. Brownie marzipan croissant tootsie roll bear claw sugar plum bear claw marshmallow. Brownie donut chocolate cake carrot cake liquorice cheesecake cotton candy. Sugar plum dessert tart sugar plum. Toffee gingerbread cookie sugar plum. Biscuit chocolate bar gingerbread gummies.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
<<<<<<< HEAD
theme: minima
=======
theme: jekyll-theme-modernist
>>>>>>> cca194afd0faf16007d6743a830b6732f1b104bd
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
